tcmrj_tickets/category/urls.py
from tcmrj_tickets.category.views import *

from django.urls import path

app_name = 'category'
urlpatterns = [
    path('getsubcategory', get_subcategory, name='getsubcategory'),

    path('list', CategoryListView.as_view(), name='list'), 
    path('create', CategoryCreateView.as_view(), name='create'),    
    path('<int:pk>/update/', CategoryUpdateView.as_view(), name='update'),
    path('<int:pk>/detail/', CategoryDatailView.as_view(), name='detail'),   
    path('<int:pk>/delete/', CategoryDeleteView.as_view(), name='delete'),

    path('subcategoria/list', SubCategoryListView.as_view(), name='sub_list'), 
    path('subcategoria/create', SubCategoryCreateView.as_view(), name='sub_create'),    
    path('<int:pk>/subcategoria/update/', SubCategoryUpdateView.as_view(), name='sub_update'),
    path('<int:pk>/subcategoria/detail/', SubCategoryDatailView.as_view(), name='sub_detail'),   
    path('<int:pk>/subcategoria/delete/', SubCategoryDeleteView.as_view(), name='sub_delete'),

]

tcmrj_tickets/core/urls.py
from tcmrj_tickets.core.views import ger_tickets, home
from django.urls import path

app_name = 'core'
urlpatterns = [
    path('', home, name='home'),
    path('gerenciamento', ger_tickets, name='gerenciamento'),
]

tcmrj_tickets/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('accounts/', include('tcmrj_tickets.accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('', include('tcmrj_tickets.core.urls', namespace='core')),   
    path('api/', include('tcmrj_tickets.api.urls', namespace='rest_framework')),
    path('chamados/', include('tcmrj_tickets.tickets.urls', namespace='tickets')),
    path('categoria/', include('tcmrj_tickets.category.urls', namespace='category')),
]

tcmrj_tickets/category/models.py
from django.db import models
from django.shortcuts import resolve_url as r
from tcmrj_tickets.core.models import ModelCreatedByMixin


# Create your models here.
class Category(ModelCreatedByMixin):
    name = models.CharField('Nome da Categoria', max_length=150)

    class Meta:
        verbose_name_plural = 'Categorias'
        verbose_name = 'Categoria'
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return r('category:detail', pk=self.id)



class SubCategory(ModelCreatedByMixin):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='subcategory_parent')
    name = models.CharField(verbose_name='Nome da Sub Categoria', max_length=150)
    
    class Meta:
        verbose_name_plural = 'Sub Categorias'
        verbose_name = 'Sub Categoria'
        ordering = ['category']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return r('category:sub_detail', pk=self.id)

tcmrj_tickets/category/forms.py
from django import forms
from .models import Category, SubCategory


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']


class SubCategoryForm(forms.ModelForm):
    class Meta:
        model = SubCategory
        fields = ['category', 'name']

tcmrj_tickets/category/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required
from tcmrj_tickets.core.decorators import group_required
from django.utils.decorators import method_decorator
from tcmrj_tickets.category.forms import CategoryForm, SubCategoryForm
from tcmrj_tickets.category.models import Category, SubCategory
from django.urls import reverse_lazy
from django.http import HttpResponse
import json
from tcmrj_tickets.core.mixins import ViewCreatedByMixin, MessageSuccessDeleteView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView


@login_required
def get_subcategory(request):
    pk = request.GET.get('pk')
    result = list(SubCategory.objects.filter(category_id=pk).values('id', 'name'))
    return HttpResponse(json.dumps(result), content_type="application/json")


decorators = [login_required, group_required('gestor')]
@method_decorator(decorators, name='dispatch')
class CategoryCreateView(ViewCreatedByMixin, SuccessMessageMixin, CreateView):
    template_name = 'category/category_form.html'
    model = Category
    form_class = CategoryForm
    success_url = reverse_lazy('category:list')
    success_message = "Categoria criada com sucesso!"


decorators = [login_required, group_required('gestor')]
@method_decorator(decorators, name='dispatch')
class CategoryUpdateView(SuccessMessageMixin, UpdateView):
    template_name = 'category/category_form.html'
    model = Category
    form_class = CategoryForm
    success_url = reverse_lazy('category:list')
    success_message = "Categoria atualizada com sucesso!"
    

decorators = [login_required, group_required('gestor')]
@method_decorator(decorators, name='dispatch')
class CategoryListView(ListView):
    template_name = 'category/category_list.html'
    model = Category
    paginate_by = 10


decorators = [login_required, group_required('gestor')]
@method_decorator(decorators, name='dispatch')
class CategoryDatailView(DetailView):
    template_name = 'category/category_detail.html'
    model = Category
    

decorators = [login_required, group_required('gestor')]
@method_decorator(decorators, name='dispatch')
class CategoryDeleteView(MessageSuccessDeleteView):
    template_name = 'category/category_delete.html'
    model = Category
    success_url = reverse_lazy('category:list')
    success_message = "Categoria deletada com sucesso!"


"""SUB CATEORIAS"""

decorators = [login_required, group_required('gestor')]
@method_decorator(decorators, name='dispatch')
class SubCategoryCreateView(ViewCreatedByMixin, SuccessMessageMixin, CreateView):
    template_name = 'subcategory/subcategory_form.html'
    model = SubCategory
    form_class = SubCategoryForm
    success_url = reverse_lazy('category:sub_list')
    success_message = "Subcategoria criada com sucesso!"


decorators = [login_required, group_required('gestor')]
@method_decorator(decorators, name='dispatch')
class SubCategoryUpdateView(SuccessMessageMixin, UpdateView):
    template_name = 'subcategory/subcategory_form.html'
    model = SubCategory
    form_class = SubCategoryForm
    success_url = reverse_lazy('category:sub_list')
    success_message = "Subcategoria atualizada com sucesso!"


decorators = [login_required, group_required('gestor')]
@method_decorator(decorators, name='dispatch')
class SubCategoryListView(ListView):
    template_name = 'subcategory/subcategory_list.html'
    model = SubCategory
    paginate_by = 10


@method_decorator(login_required, name='dispatch')
@method_decorator(group_required('gestor'), name='dispatch')
class SubCategoryDatailView(DetailView):
    template_name = 'subcategory/subcategory_detail.html'
    model = SubCategory


@method_decorator(login_required, name='dispatch')
@method_decorator(group_required('gestor'), name='dispatch')
class SubCategoryDeleteView(MessageSuccessDeleteView):
    template_name = 'subcategory/subcategory_delete.html'
    model = SubCategory
    success_url = reverse_lazy('category:sub_list')
    success_message = "Subcategoria excluída com sucesso!"

tcmrj_tickets/category/templates/category/category_delete.html
{% extends "base.html" %}

{% block title %} Deleta Categoria {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <form method="post">{% csrf_token %}
            <p>Tem Certeza que deseja deletar a Categoria "{{ object }}"?</p>
            <button type="submit" class="btn btn-danger">
                <span class="material-icons align-middle">delete</span>
                <span class="align-middle">Deletar</span>
            </button>
        </form>
    </div>
</div>    
{% endblock %}

tcmrj_tickets/category/templates/category/category_detail.html
{% extends "base.html" %}

{% block title %}Detalhe de Categorias{% endblock %}

{% block content %}
<div class="container">
        <div class="card">
            <h5 class="card-header text-center">
                Categoria: {{category.name}}
            </h5>
            <div class="card-body">
                <h5 class="card-title">Detalhes</h5>
                <div class="card-text">
                    <div>
                        <p><b>id: </b>{{ category.id }}</p>
                        <p><b>Nome: </b>{{ category.name }}</p>
                        <p><b>Criador: </b>{{ category.created_by }}</p>                 
                        <p><b>Criado: </b>{{ category.created_at }}</p>
                        <p><b>Modificado: </b>{{ category.updated_at }}</p>
                    </div>
                </div>
            </div>
            <div class="card-footer text-center">
                <a class="btn btn-secondary" href="{% url 'category:list' %}" alt="ver" >
                    <span class="material-icons md-18 align-middle">arrow_back</span>
                    <span>voltar</span>
                </a>
                <a class="btn btn-success" href="{% url 'category:update' category.id %}">
                    <span class="material-icons md-18 align-middle">edit</span>
                    <span>editar</span>
                </a>
                <a class="btn btn-danger" href="{% url 'category:delete' category.id %}">
                    <span class="material-icons md-18 align-middle">delete</span>
                    <span>deletar</span>
                </a>
            </div>
        </div>
</div>
{% endblock %}

tcmrj_tickets/category/templates/category/category_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}
    {% if category %}
        Autaliza Categoria: "{{ category.id }}"
    {% else %}
        Nova Categoria
    {% endif %}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <form method="post">
            {% csrf_token %}
            <fieldset class="fieldset-forms row col-6">
                <legend class="">
                    {% if category %}
                        Atualiza Categoria: "{{ category.id }}"
                    {% else %}
                        Nova Categoria
                    {% endif %}
                </legend>
                <div class="col-12">
                    <label for="{{ form.name.id_for_label }}" class="form-label">{{ form.name.label }}</label>
                    {{ form.name.errors }}
                    {{ form.name|add_class:'form-control'}}
                </div>
                
            </fieldset>
            <br>
            <div class="form-group">
                <button type="submit" class="btn btn-success">
                    <span class="material-icons align-middle">save</span>
                    <span class="align-middle">Salvar</span>
                </button>
                <a class="btn btn-secondary" href="{% url 'category:list' %}" alt="ver" >
                    <span class="material-icons md-18 align-middle">arrow_back</span>
                    <span>voltar</span>
                </a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

tcmrj_tickets/category/templates/category/category_list.html
{% extends "base.html" %}

{% block title %}Gereciamento de Chamados - Lista de Categorias{% endblock %}

{% block content %}
<div class="container">
    <div class="row col-12">
        <h4>Gereciamento de Chamados - Lista de Categorias</h4>
    </div>
    <br><br>
    <div class="row col-12">
        <table class="table table-light table-striped">
            <thead>
                <tr>
                    <th scope="col">id</th>
                    <th scope="col">Nome</th>
                    <th scope="col">Ações</th>
                </tr>
            </thead>
            <tbody>
                {% for category in object_list %}
                <tr>
                    <th scope="row">{{ category.id }}</th>
                    <td>{{ category.name }}</td>
                    <td class="td_actions">
                        <a class="btn btn-primary" href="{% url 'category:detail' category.id %}" alt="ver" >
                            <span class="material-icons md-18 align-middle">visibility</span>
                            <span>ver</span>
                        </a>
                        <a class="btn btn-success" href="{% url 'category:update' category.id %}">
                            <span class="material-icons md-18 align-middle">edit</span>
                            <span>editar</span>
                        </a>
                        <a class="btn btn-danger" href="{% url 'category:delete' category.id %}">
                            <span class="material-icons md-18 align-middle">delete</span>
                            <span>deletar</span>
                        </a>
                    </td>
                </tr>
                {% empty %}
                    <p>Não há categorias na base de dados.</p>
                {% endfor %}
            </tbody>
        </table>
        {% include "pagination.html" with page=page_obj %}
        <br><br>
    </div>
    <a class="btn btn-primary" href="{% url 'category:create' %}" alt="Adicionar" >
        <span class="material-icons md-18 align-middle">add</span>
        <span>Adicionar Categoria</span>
    </a>
    <a class="btn btn-primary" href="{% url 'category:sub_create' %}" alt="Adicionar" >
        <span class="material-icons md-18 align-middle">add</span>
        <span>Adicionar Sub-Categoria</span>
    </a>
    <a class="btn btn-secondary" href="{% url 'core:gerenciamento' %}" alt="ver" >
        <span class="material-icons md-18 align-middle">arrow_back</span>
        <span>voltar - Gerenciamento</span>
    </a>
</div>
{% endblock %}