tcmrj_tickets/category/urls.py
from tcmrj_tickets.category.views import *

from django.urls import path

app_name = 'category'
urlpatterns = [
    path('getsubcategory', get_subcategory, name='getsubcategory'),

    path('list', CategoryListView.as_view(), name='list'), 
    path('create', CategoryCreateView.as_view(), name='create'),    
    path('<int:pk>/update/', CategoryUpdateView.as_view(), name='update'),
    path('<int:pk>/detail/', CategoryDatailView.as_view(), name='detail'),   
    path('<int:pk>/delete/', CategoryDeleteView.as_view(), name='delete'),

    path('subcategoria/list', SubCategoryListView.as_view(), name='sub_list'), 
    path('subcategoria/create', SubCategoryCreateView.as_view(), name='sub_create'),    
    path('<int:pk>/subcategoria/update/', SubCategoryUpdateView.as_view(), name='sub_update'),
    path('<int:pk>/subcategoria/detail/', SubCategoryDatailView.as_view(), name='sub_detail'),   
    path('<int:pk>/subcategoria/delete/', SubCategoryDeleteView.as_view(), name='sub_delete'),

]

tcmrj_tickets/core/urls.py
from tcmrj_tickets.core.views import ger_tickets, home
from django.urls import path

app_name = 'core'
urlpatterns = [
    path('', home, name='home'),
    path('gerenciamento', ger_tickets, name='gerenciamento'),
]

tcmrj_tickets/tickets/urls.py
from tcmrj_tickets.tickets.views import *
from django.urls import path

app_name = 'tickets'
urlpatterns = [
    path('list', TicketListView.as_view(), name='list'), 
    path('create', TicketCreateView.as_view(), name='create'),    
    path('<int:pk>/update/', TicketUpdateView.as_view(), name='update'),
    path('<int:pk>/detail/', TicketDatailView.as_view(), name='detail'),   
    path('<int:pk>/delete/', TicketDeleteView.as_view(), name='delete'),

    path('responsavel/list', SolverListView.as_view(), name='solver_list'), 
    path('responsavel/create', SolverCreateView.as_view(), name='solver_create'),    
    path('<int:pk>/responsavel/update/', SolverUpdateView.as_view(), name='solver_update'),
    path('<int:pk>/responsavel/detail/', SolverDatailView.as_view(), name='solver_detail'),   
    path('<int:pk>/responsavel/delete/', SolverDeleteView.as_view(), name='solver_delete'),

]

tcmrj_tickets/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('accounts/', include('tcmrj_tickets.accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('', include('tcmrj_tickets.core.urls', namespace='core')),   
    path('api/', include('tcmrj_tickets.api.urls', namespace='rest_framework')),
    path('chamados/', include('tcmrj_tickets.tickets.urls', namespace='tickets')),
    path('categoria/', include('tcmrj_tickets.category.urls', namespace='category')),
]

tcmrj_tickets/tickets/models.py
from django.db import models
from django.shortcuts import resolve_url as r
from tcmrj_tickets.core.models import ModelCreatedByMixin
from tcmrj_tickets.category.models import Category, SubCategory
from simple_history.models import HistoricalRecords


class Solver(ModelCreatedByMixin):
    name = models.CharField('Responsável', max_length=255)

    class Meta:
        verbose_name_plural = 'Responsáveis'
        verbose_name = 'Responsável'
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return r('tickets:solver_detail', pk=self.id)


class Ticket(ModelCreatedByMixin):
    ABERTO = 'Aberto'
    EMANDAMENTO = 'Em Andamento'
    CONCLUIDO = 'Concluído'

    STATUS_CHOICES = [
        (ABERTO, 'Aberto'),
        (EMANDAMENTO, 'Em Andamento'),
        (CONCLUIDO, 'Concluído'),
    ]

    status = models.CharField(max_length=12, choices=STATUS_CHOICES, default='Aberto', verbose_name='Status')
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING, related_name='tickets_category', verbose_name='Categoria')
    subcategory = models.ForeignKey(SubCategory, on_delete=models.DO_NOTHING, related_name='tickets_subcategory', verbose_name='Sub Categoria', blank=True, null=True)
    solver = models.ForeignKey(Solver, on_delete=models.DO_NOTHING, verbose_name='Responsável')
    description = models.TextField(verbose_name='Descrição')
    history = HistoricalRecords()
    

    class Meta:
        verbose_name_plural = 'Chamados'
        verbose_name = 'chamado'
        ordering = ['-id']

    def __str__(self):
        return str(self.id)

    def get_absolute_url(self):
        return r('tickets:detail', pk=self.id)

tcmrj_tickets/tickets/forms.py
from django import forms

from .models import Solver, Ticket


class SolverForm(forms.ModelForm):
    class Meta:
        model = Solver
        fields = ['name']


class TicketForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ['category', 'subcategory', 'solver', 'description']


class TicketManagerForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ['status', 'category', 'subcategory', 'solver', 'description']
    

class TicketBasicForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ['solver']

tcmrj_tickets/tickets/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required
from tcmrj_tickets.core.decorators import group_required
from django.utils.decorators import method_decorator
from tcmrj_tickets.tickets.forms import TicketForm, SolverForm
from tcmrj_tickets.tickets.models import Ticket, Solver
from tcmrj_tickets.tickets.mixins import TicketUpdateMixin, TicketListMixin
from django.urls import reverse_lazy
from tcmrj_tickets.core.mixins import ViewCreatedByMixin, MessageSuccessDeleteView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView


@method_decorator(login_required, name='dispatch')
class TicketCreateView(SuccessMessageMixin, ViewCreatedByMixin, CreateView):
    template_name = 'tickets/tickets_form.html'
    model = Ticket
    form_class = TicketForm
    success_url = reverse_lazy('tickets:list')
    success_message = "Chamado criado com sucesso!"


decorators = [login_required, group_required('gestor', 'suporte')]
@method_decorator(decorators, name='dispatch')
class TicketUpdateView(SuccessMessageMixin, TicketUpdateMixin, UpdateView):
    template_name = 'tickets/tickets_form.html'
    model = Ticket
    success_url = reverse_lazy('tickets:list')
    success_message = "Chamado atualizado com sucesso!"
    
@method_decorator(login_required, name='dispatch')
class TicketListView(TicketListMixin, ListView):
    template_name = 'tickets/tickets_list.html'
    model = Ticket
    paginate_by = 100

    
@method_decorator(login_required, name='dispatch')
class TicketDatailView(DetailView):
    template_name = 'tickets/tickets_detail.html'
    model = Ticket
    

decorators = [login_required, group_required('gestor')]
@method_decorator(decorators, name='dispatch')
class TicketDeleteView(MessageSuccessDeleteView):
    template_name = 'tickets/tickets_delete.html'
    model = Ticket
    success_url = reverse_lazy('tickets:list')
    success_message = "Chamado excluído com sucesso!"

""" SOLVER VIEWS"""

decorators = [login_required, group_required('gestor')]
@method_decorator(decorators, name='dispatch')
class SolverCreateView(ViewCreatedByMixin, SuccessMessageMixin, CreateView):
    template_name = 'solver/solver_form.html'
    model = Solver
    form_class = SolverForm
    success_url = reverse_lazy('tickets:solver_list')
    success_message = "Responsável criado com sucesso!"



decorators = [login_required, group_required('gestor')]
@method_decorator(decorators, name='dispatch')
class SolverUpdateView(SuccessMessageMixin, UpdateView):
    template_name = 'solver/solver_form.html'
    model = Solver
    form_class = SolverForm
    success_url = reverse_lazy('tickets:solver_list')
    success_message = "Responsável atualizado com sucesso!"

decorators = [login_required, group_required('gestor')]
@method_decorator(decorators, name='dispatch')
class SolverListView(ListView):
    template_name = 'solver/solver_list.html'
    model = Solver
    paginate_by = 10


decorators = [login_required, group_required('gestor')]
@method_decorator(decorators, name='dispatch')
class SolverDatailView(DetailView):
    template_name = 'solver/solver_detail.html'
    model = Solver


decorators = [login_required, group_required('gestor')]
@method_decorator(decorators, name='dispatch')
class SolverDeleteView(MessageSuccessDeleteView):
    template_name = 'solver/solver_delete.html'
    model = Solver
    success_url = reverse_lazy('tickets:solver_list')
    success_message = "Responsável excluído com sucesso!"

tcmrj_tickets/tickets/templates/tickets/tickets_delete.html
{% extends "base.html" %}

{% block title %} Deleta Chamado {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <form method="post">{% csrf_token %}
            <p>Tem Certeza que deseja deletar o Chamado "{{ object }}"?</p>
            <button type="submit" class="btn btn-danger">
                <span class="material-icons align-middle">delete</span>
                <span class="align-middle">Deletar</span>
            </button>
        </form>
    </div>
</div>    
{% endblock %}

tcmrj_tickets/tickets/templates/tickets/tickets_detail.html
{% extends "base.html" %}
{% load core_extras %}

{% block title %}Lista de Chamados{% endblock %}

{% block content %}
<div class="container">
    <div class="card">
        <h5 class="card-header text-center">
            Chamado: {{ticket.id}}
        </h5>
        <div class="card-body">
            <h5 class="card-title">Detalhes</h5>
            <div class="card-text">
                <div class="">
                    <p><b>Abertura: </b>{{ ticket.created_at }}</p>
                    <p><b>Status: </b>{{ ticket.status }}</p>
                    <p><b>Categoria: </b>{{ ticket.category }}</p>
                    <p><b>Sub-Categoria: </b>{% firstof ticket.subcategory "" %}</p>
                    <p><b>Responsável: </b>{{ ticket.solver }}</p>
                    <p><b>Descrição:</b></p>
                    <p>{{ ticket.description }}</p>
                </div>
            </div>
        </div>
        <div class="card-footer text-center">
            <a class="btn btn-secondary" href="{% url 'tickets:list' %}" alt="ver" >
                <span class="material-icons md-18 align-middle">arrow_back</span>
                <span>voltar</span>
            </a>
            {% if request.user|has_groups:"gestor,suporte" %}
            <a class="btn btn-success" href="{% url 'tickets:update' ticket.id %}">
                <span class="material-icons md-18 align-middle">edit</span>
                <span>editar</span>
            </a>
            {% endif %}
            {% if request.user|has_groups:"gestor" %}
            <a class="btn btn-danger" href="{% url 'tickets:delete' ticket.id %}">
                <span class="material-icons md-18 align-middle">delete</span>
                <span>deletar</span>
            </a>
            {% endif %}
        </div>
    </div>
    <br><br>
    <div class="history_container">
        <h5>Histórico de Atualização:</h5>
        <hr>
        {% for h in ticket.history.all %}
           <p>
               <b>Atualizado em: </b>{{h.history_date}}<b> - 
               Status: </b>{{ h.status }} - 
               <b>Responsável: </b>{{ h.solver }}
            </p>
        {% empty %}
            <p>Não há atualizações.</p>
        {% endfor %}
    </div>
</div>
{% endblock %}

tcmrj_tickets/tickets/templates/tickets/tickets_form.html
{% extends "base.html" %}
{% load widget_tweaks %}


{% block title %}
    {% if ticket %}
        Autaliza Chamado: "{{ ticket.id }}"
    {% else %}
        Novo Chamado
    {% endif %}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <form method="post">
            {% csrf_token %}
            <fieldset class="fieldset-forms row col-6">
                <legend class="">
                    {% if ticket %}
                        Atualiza Chamado: "{{ ticket.id }}"
                    {% else %}
                        Novo Chamado
                    {% endif %}
                </legend>
                <div class="col-12">
                    <label for="{{ form.status.id_for_label }}" class="form-label">{{ form.status.label }}</label>
                    {{ form.status.errors }}
                    {{ form.status|add_class:'form-select' }}
                </div>
                <div class="col-12">
                    <label for="{{ form.category.id_for_label }}" class="form-label">{{ form.category.label }}</label>
                    {{ form.category.errors }}
                    {{ form.category|add_class:'form-select' }}
                </div>
                <div class="col-12">
                    <label for="{{ form.subcategory.id_for_label }}" class="form-label">{{ form.subcategory.label }}</label>
                    {{ form.subcategory.errors }}
                    {{ form.subcategory|add_class:'form-select' }}
                </div>
                <div class="col-12">
                    <label for="{{ form.solver.id_for_label }}" class="form-label">{{ form.solver.label }}</label>
                    {{ form.solver.errors }}
                    {{ form.solver|add_class:'form-select' }}
                </div>
                <div class="col-12">
                    <label for="{{ form.description.id_for_label }}" class="form-label">{{ form.description.label }}</label>
                    {{ form.description.errors }}
                    {{ form.description|add_class:'form-control' }}
                </div>
            </fieldset>
            <br>
            <div class="form-group">
                <button type="submit" class="btn btn-success">
                    <span class="material-icons align-middle">save</span>
                    <span class="align-middle">Salvar</span>
                </button>
                <a class="btn btn-secondary" href="{% url 'tickets:list' %}" alt="ver" >
                    <span class="material-icons md-18 align-middle">arrow_back</span>
                    <span>voltar</span>
                </a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block js_internal_include %}

$(document).ready(function () {
    //remove todos os options da subcategoria meno o selecionado
    //$('#id_subcategory').children('option:not(:selected)').remove();
    
    if( $('#id_category').length )  {
        {% if ticket %}
            var id_category = $("#id_category").val();
            var id_subcategory_selected = $('#id_subcategory').val();
            $('#id_subcategory').children().remove();
            getSubCategories(id_category, id_subcategory_selected);
        {% endif %}

        
        $("#id_category").change(function () {
            var id_category = $(this).val()
            if(!id_category){
                return;
            }
            $('#id_subcategory').children().remove();
            getSubCategories(id_category);
        });

        function getSubCategories(id_category, id_subcategory_selected = ""){
            $.ajax({
                url: "{% url 'category:getsubcategory' %}",
                data: {pk: id_category},
                type: 'get',
                success: function(data) {
                    if(data !== 'undefined' && data !== ''){
                        $("#id_subcategory").append($("<option></option>").attr("value", "").text("---------"));
                        for(var k in data) {
                            id = data[k]["id"];
                            name = data[k]["name"];
                            if(id == id_subcategory_selected){
                                var selected = "selected";
                            }else{
                                var selected = "";
                            }
                            $("#id_subcategory").append("<option value='"+id+"' " +selected+" >"+name+"</option>");
                        }
                    }
                        
                },
                failure: function(data) { 
                    conole.log('erro no ajax');
                }
            });
        }
    }
});

{% endblock %}

tcmrj_tickets/tickets/templates/tickets/tickets_list.html
{% extends "base.html" %}
{% load core_extras %}

{% block title %}Lista de Chamados{% endblock %}

{% block content %}
<div class="container">
    <div class="row col-12">
        <h4>Lista de Chamados</h4>
    </div>
    <br><br>
    <div class="row col-12">
        <table class="table table-light table-striped">
            <thead>
                <tr>
                    <th scope="col">Chamado</th>
                    <th scope="col">Abertura</th>
                    <th scope="col">Status</th>
                    <th scope="col">Categoria</th>
                    <th scope="col">Subcategoria</th>
                    <th scope="col">Responsável</th>
                    <th scope="col">Ações</th>
                </tr>
            </thead>
            <tbody>
                {% for ticket in object_list %}
                <tr>
                    <th scope="row">{{ ticket.id }}</th>
                    <td>{{ ticket.created_at }}</td>
                    <td>{{ ticket.status }}</td>
                    <td>{{ ticket.category }}</td>
                    <td>{{ ticket.subcategory|default:"" }}</td>
                    <td>{{ ticket.solver }}</td>
                    <td class="td_actions">
                        <a class="btn btn-primary" href="{% url 'tickets:detail' ticket.id %}" alt="ver" >
                            <span class="material-icons md-18 align-middle">visibility</span>
                            <span>ver</span>
                        </a>
                        {% if request.user|has_groups:"gestor,suporte" %}
                        <a class="btn btn-success" href="{% url 'tickets:update' ticket.id %}">
                            <span class="material-icons md-18 align-middle">edit</span>
                            <span>editar</span>
                        </a>
                        {% endif %}
                        {% if request.user|has_groups:"gestor" %}
                        <a class="btn btn-danger" href="{% url 'tickets:delete' ticket.id %}">
                            <span class="material-icons md-18 align-middle">delete</span>
                            <span>deletar</span>
                        </a>
                        {% endif %}
                    </td>
                </tr>
                {% empty %}
                    <p>Não há chamados na base de dados.</p>
                {% endfor %}
            </tbody>
        </table>
        {% include "pagination.html" with page=page_obj %}
        <br><br>
    </div>
    <a class="btn btn-primary" href="{% url 'tickets:create' %}" alt="Adicionar" >
        <span class="material-icons md-18 align-middle">add</span>
        <span>Adicionar Chamado</span>
    </a>
    {% if request.user|has_groups:"gestor" %}
    <a class="btn btn-secondary" href="{% url 'core:gerenciamento' %}" alt="ver" >
        <span class="material-icons md-18 align-middle">arrow_back</span>
        <span>voltar - Gerenciamento</span>
    </a>
    {% endif %}
</div>
{% endblock %}