tcmrj_tickets/core/urls.py
from tcmrj_tickets.core.views import ger_tickets, home
from django.urls import path

app_name = 'core'
urlpatterns = [
    path('', home, name='home'),
    path('gerenciamento', ger_tickets, name='gerenciamento'),
]

tcmrj_tickets/tickets/urls.py
from tcmrj_tickets.tickets.views import *
from django.urls import path

app_name = 'tickets'
urlpatterns = [
    path('list', TicketListView.as_view(), name='list'), 
    path('create', TicketCreateView.as_view(), name='create'),    
    path('<int:pk>/update/', TicketUpdateView.as_view(), name='update'),
    path('<int:pk>/detail/', TicketDatailView.as_view(), name='detail'),   
    path('<int:pk>/delete/', TicketDeleteView.as_view(), name='delete'),

    path('responsavel/list', SolverListView.as_view(), name='solver_list'), 
    path('responsavel/create', SolverCreateView.as_view(), name='solver_create'),    
    path('<int:pk>/responsavel/update/', SolverUpdateView.as_view(), name='solver_update'),
    path('<int:pk>/responsavel/detail/', SolverDatailView.as_view(), name='solver_detail'),   
    path('<int:pk>/responsavel/delete/', SolverDeleteView.as_view(), name='solver_delete'),

]

tcmrj_tickets/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('accounts/', include('tcmrj_tickets.accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('', include('tcmrj_tickets.core.urls', namespace='core')),   
    path('api/', include('tcmrj_tickets.api.urls', namespace='rest_framework')),
    path('chamados/', include('tcmrj_tickets.tickets.urls', namespace='tickets')),
    path('categoria/', include('tcmrj_tickets.category.urls', namespace='category')),
]

tcmrj_tickets/core/models.py
from django.db import models
from django.shortcuts import resolve_url as r
from django.contrib.auth.models import User


class ModelCreatedByMixin(models.Model):
    created_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, verbose_name='Criado por')
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)

    class Meta:
        abstract = True

tcmrj_tickets/core/views.py
from django.shortcuts import render
from tcmrj_tickets.core.decorators import group_required
from django.contrib.auth.decorators import login_required
from tcmrj_tickets.tickets.models import Ticket
from django.db.models import Count

@login_required
def home(request):
    """Home principal do sistema"""
    return render(request, 'core/home.html')


@login_required
@group_required('gestor')
def ger_tickets(request):
    """Home do Gerenciamento de chamados"""
    return render(request, 'core/gerenciamento_chamados.html')

tcmrj_tickets/core/templates/base.html
{% load static %}
{% load core_extras %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="description" content="Sistema de Abertura de Chamados">
    <meta name="author" content="msbar">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    
    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'img/favicon.png' %}">

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% block css_file_include %}{% endblock %}
    {% block css_internal_include %}{% endblock %}

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    
    <!-- JQUERY UI-->
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="{% static 'js/main.js' %}"></script>

    <!-- Icons-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css">

    

    <title>{% block title %}{% endblock title %} | TCMRJ Ticket</title>
</head>
<body>
    <header>
        {% include 'header.html' %}
    </header>
    <aside id="sidebar">
        {% include 'sidebar-menu.html' %}
    </aside>
    <main>
        {% block content %}
        {% endblock content %}
        
        {% if messages %}
        <div class="messages toast-container position-absolute bottom-0 end-0 p-3"  id="toastPlacement">
        {% for message in messages %}
            <div class="toast align-items-center text-white bg-{{ message.tags }} border-0" role="alert" aria-live="assertive" aria-atomic="true">
                <div class="d-flex">
                    <div class="toast-body">
                        {{ message|safe }}
                    </div>
                    <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
            </div>      
        {% endfor %}
        </div>
        {% endif %}
    </main>
    
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    {% block js_file_include %}{% endblock %}
    <script type="text/javascript">{% block js_internal_include %} {% endblock %}</script>
    

</body>
</html>

tcmrj_tickets/core/templates/base_blank.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="description" content="Sistema de Abertura de Chamados">
    <meta name="author" content="msbar">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    
    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'img/favicon.png' %}">

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% block css_file_include %}{% endblock %}

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    
    <!-- JQUERY UI-->
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="{% static 'js/main.js' %}"></script>

    <!-- Icons-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css">

    <title>{% block title %}{% endblock title %} | TCMRJ Ticket</title>
</head>
<body>
    
    {% if messages %}
        <ul class="messages">
        {% for message in messages %}
            <li class="{{ message.tags }}">
                {{ message|safe }}
                <a href="#" class="close">x</a>
            </li>
        {% endfor %}
        </ul>
    {% endif %}
    {% block content %}
    {% endblock content %}
   

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script type="text/javascript">{% block js_internal_include %} {% endblock %}</script>
    {% block js_file_include %}{% endblock %}

</body>
</html>

tcmrj_tickets/core/templates/header.html
<div class="right_area">
    <div class="user-info">
        Usuário: <span>{{ user.get_username }}</span>
    </div>
    <div class="user-info">
        Função: <span>{{ user.groups.all.0 }}</span>
    </div>
    <div class="btn-group">
        <button class="btn btn-dark btn-sm" type="button" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="material-icons">person</i>
        </button>
        <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuButton2">
            <li><a class="dropdown-item active" href="#">Profile</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">logout</a></li>
          </ul>
    </div>
    
</div>

tcmrj_tickets/core/templates/pagination.html
<nav>
  	<ul class="pagination pagination-sm justify-content-right">
		
		{% if page.has_previous %}
			<li class="page-item">
				<a class="page-link" tabindex="-1" aria-disabled="true" href="?page={{ page.previous_page_number }}">Previous</a>
			</li>
		{% else %}
			<li class="page-item disabled">
				<a class="page-link" tabindex="-1" aria-disabled="true" href="#">Previous</a>
			</li>
		{% endif %}
			
		
		<li class="page-item active" aria-current="page">
			<a class="page-link" href="#">Page {{ page.number }} of {{ page.paginator.num_pages }}.</a>
		</li>

		
		{% if page.has_next %}
			<li class="page-item">
				<a class="page-link" href="?page={{ page.next_page_number }}">Next</a>
			</li>
		{% else %}
			<li class="page-item disabled">
				<a class="page-link" tabindex="-1" aria-disabled="true" href="#">Next</a>
			</li>
		{% endif %}
	</ul>
</nav>

tcmrj_tickets/core/templates/sidebar-menu.html
{% load core_extras %}
{% load static %}
<div class="logo-datails">
    <span class="material-icons" id="btn-menu">menu</span>
    <h3><img src="{% static 'img/tcmrj.png' %}"></h3>
</div>
<div class="sidebar-menu">                    
    <div class="sidebar-menu">
        <div class="menu-item">
            <a href="{% url 'core:home' %}" class="menu-item-link">
                <i class="material-icons">home</i>
                <span>Home</span>
            </a>
        </div>
        <div class="menu-item">            
            <a href="#" class="menu-item-link">
                <i class="material-icons">description</i>
                <span>Ticket<i class="material-icons">chevron_right</i></span>
            </a>
            <div class="submenu-item">
                <a href="{% url 'tickets:list' %}">Consulta de Chamado</a>
                <a href="{% url 'tickets:create' %}">Abertura de Chamado</a>
                {% if request.user|has_groups:"gestor" %}
                    <a href="{% url 'core:gerenciamento' %}">Gerenciamento de Chamado</a>
                {% endif %}
            </div>
        </div>
        {% if request.user|has_groups:"gestor" %}
        <div class="menu-item">
            <a href="#" class="menu-item-link">
                <i class="material-icons">people</i>
                <span>Usuários</span>
            </a>
        </div>
        {% endif %}
        
</div>